name: Status check for packer template
on: [pull_request]
jobs:
    status-check:
        runs-on: ubuntu-latest
        env:
            GITHUB_WORKSPACE: ${{ github.workspace }}
            PRODUCT_VERSION: 1.1.1
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup `packer`
              uses: hashicorp/setup-packer@main
              id: setup
              with:
                version: $PRODUCT_VERSION
            - name: Status Check for packer template
              run: |
                echo $GITHUB_WORKSPACE
                packer fmt $GITHUB_WORKSPACE/packer/centos.pkr.hcl --check
                packer validate $GITHUB_WORKSPACE/packer/centos.pkr.hcl