name: Build Packer Template
on:
    pull_request:
        types:
            - closed
jobs:
    if-merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        env:
            DB_HOST: ${{ vars.DB_HOST }}
            DB_PORT: ${{ vars.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_SCHEMA: ${{ vars.DB_SCHEMA }}
            DB_DIALECT: ${{ vars.DB_DIALECT }}
            DB_TIMEZONE: ${{ vars.DB_TIMEZONE }}  
            GITHUB_WORKSPACE: ${{ github.workspace }}
        steps:
            - name: Setup MYSQL
              run: |
                sudo /lib/systemd/systemd-sysv-install enable mysql
                sudo systemctl enable mysql.service
                sudo systemctl start mysql.service
                sudo systemctl status mysql.service
                sudo mysql --user=$DB_USER --password=$DB_PASSWORD -e "CREATE DATABASE $DB_SCHEMA"
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            - name: Install Dependencies
              run: npm install
            - name: Run Integration Tests
              run: npm test 
            - name: Zip Repository
              run: zip -r webapp.zip .
            - name: Set up Packer
              uses: hashicorp/setup-packer@v1
              with:
                  version: 1.1.1
            - name: Build Packer Template
              run: packer build $GITHUB_WORKSPACE/packer/centos.pkr.hcl