name: Run Integration Tests
on: [pull_request]
jobs:
  install-mysql-server:
    runs-on: ubuntu-latest
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3307
          mysql version: '8.0'
          mysql database: 'mydb'
          mysql user: 'tanmay'
          mysql password: ${{ secrets.UserPassword }}
          mysql root password: ${{ secrets.RootPassword }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm test
      - run: echo "Integration tests passed successfully!"
          
      
