name: Run Integration Tests
on: [pull_request]
jobs:
  install-mysql-server:
    runs-on: ubuntu-latest
    env:
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_SCHEMA: mydb
      DB_DIALECT: mysql
      DB_TIMEZONE: -05:00
    steps:
      - name: Set up MySQL
        run: |
         sudo /lib/systemd/systemd-sysv-install enable mysql
         sudo systemctl enable mysql.service
         sudo systemctl start mysql.service
         sudo systemctl status mysql.service
         sudo mysql -u root -p root -e "CREATE DATABASE mydb;"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm test
      - run: echo "Integration tests passed successfully!"
          
      
