name: Run Integration Tests
on: [pull_request]
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SCHEMA: ${{ vars.DB_SCHEMA }}
      DB_DIALECT: ${{ vars.DB_DIALECT }}
      DB_TIMEZONE: ${{ vars.DB_TIMEZONE }}
    steps:
      - name: Set up MySQL
        run: |
         sudo /lib/systemd/systemd-sysv-install enable mysql
         sudo systemctl enable mysql.service
         sudo systemctl start mysql.service
         sudo systemctl status mysql.service
         sudo mysql --user=$DB_USER --password=$DB_PASSWORD -e "CREATE DATABASE $DB_SCHEMA"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - name: Create a directory 
        run: |
         sudo cd /var/log
         sudo mkdir webapp
         sudo touch /webapp/webapp.log
      - run: npm test
      - run: echo "Integration tests passed successfully!"
          
      
